### ISSUE TITLE
Support epub metadata

### ISSUE THREAD

**Issue by flece** [jellyfin/jellyfin-plugin-bookshelf#11]
pls add the ability to read the metadata from epub files. maybe as a new Provider?

all my selfmade and bought books have metadata and cover embedded

thx :)

**Comment by flece** [comment]
maybe this is helping: https://github.com/vers-one/EpubReader

**Comment by dkanada** [comment]
I believe #10 implements some of this.

**Comment by oddstr13** [comment]
#10 is merged and released.
Please open a new issue if this isn't working properly, or if any metadata fields are missing.
