### ISSUE TITLE
Comic metadata isn't read from inside the file

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin-plugin-bookshelf#18]
It doesn't seem like Jellyfin is reading any of the ComicVine XML info like the docs say it should be. I have all my comic books tagged and they are not being picked up properly. Jellyfin is only showing the filename info and not pulling the covers.
I tagged all my stuff with Mylar3 and LazyLibrarian.
I see the xml file in the directory for the series and inside the CBZ files as well.

```
/mnt/storage/comics/DC Comics/Absolute Crisis On Infinite Earths (2005)/cvinfo
/mnt/storage/comics/DC Comics/Absolute Crisis On Infinite Earths (2005)/Absolute Crisis On Infinite Earths #1 (2005).cbz
```

I would upload the metadata files but GitHub won't let me.
Inside the cbz file is "ComicInfo.xml"

**Comment by tydog98** [comment]
Any update on this? My ComicInfo.xml also isn't being read despite the plugin description saying that it works.

**Comment by Protektor-Desura** [comment]
I still don't see that it is reading the xml file yet or anything other than it appears the filename.

**Comment by adamhathcock** [comment]
I've done some work over the years around comic metadata.  Lots of false starts like this: 

https://github.com/adamhathcock/CBTool/tree/master/CBTool/Metadata

This is around the format used by comicrack which is still a defacto standard.

I also believe that there is data also being stored in the message blobs in archives themselves but unsure of the format.

**Comment by MinecraftPlaye** [comment]
I currently have a basic implementation of this working in my fork of this plug-in. It might not be perfect, but it's at least something.
Does anyone know how the ComicInfo.xml handles Genres?

**Comment by Protektor-Desura** [comment]
Still having problems with Comics not being imported with any metadata at all.

**Comment by whatinthenameofgod** [comment]
Same as @Protektor-Desura. I don't get any metadata at all.

**Comment by MinecraftPlaye** [comment]
> Still having problems with Comics not being imported with any metadata at all.


> Same as @Protektor-Desura. I don't get any metadata at all.

Yeah, that's because the changes in #34 haven't been merged and released yet. They are still awaiting a review from @crobibero . ;)

**Comment by crobibero** [comment]
Sorry! My self re-review request fell through the cracks...

**Comment by MinecraftPlaye** [comment]
> Sorry! My self re-review request fell through the cracks...

No problem.
