### ISSUE TITLE
Support for ComicVine metadata

### ISSUE THREAD

**Issue by carif** [jellyfin/jellyfin-plugin-bookshelf#36]
Support for ComicVine metadata provider

Some guidelines for file naming could be useful as well. This are the guidelines `comictagger` uses to identify a comic and search for it in the ComicVine db: https://github.com/comictagger/comictagger/wiki/UserGuide

**Comment by Casuallynoted** [comment]
I'd also really like to see this!

**Comment by Protektor-Desura** [comment]
We need more than just metadata imported from the ComicVine XLM files. We actually need a ComicVine API metadata plugin. This would allow us to import story arcs.  I'm more talking about Story Arcs which will cross other comic book titles, like "Brightest Day" or "Infinity Gauntlet" or "Armor Wars 2" or whatever.

https://comicvine.gamespot.com/armor-wars/4045-55741/
https://comicvine.gamespot.com/armor-wars-ii/4045-56598/
https://comicvine.gamespot.com/brightest-day/4045-56018/
https://comicvine.gamespot.com/crisis-on-infinite-earths/4045-40764/
https://comicvine.gamespot.com/identity-crisis/4045-48398/
https://comicvine.gamespot.com/infinite-crisis/4045-40765/
https://comicvine.gamespot.com/infinite-destinies/4045-60804/
https://comicvine.gamespot.com/infinity/4045-57167/
https://comicvine.gamespot.com/infinity-gauntlet/4045-42233/

These are examples of Story Arcs in a series/title and ones where they cross across a whole bunch of different comic book titles.
