### ISSUE TITLE
always fit to window / screen

### ISSUE THREAD

**Issue by krodelabestiole** [jellyfin/jellyfin-plugin-bookshelf#49]
hello, the comics player is almost great except it always fits the page only to the height of the screen.

it works fine when the screen is wider than the page, but when the page is wider than the screen it will be cropped, instead of reducing its height.

**Comment by crobibero** [comment]
Hi, the player is not a part of this plugin, this plugin just provides metadata. I suggest filing an issue in the appropriate client repo

**Comment by krodelabestiole** [comment]
@crobibero ah ok sorry !

do you know what would be that repo ?

**Comment by crobibero** [comment]
As you didnt say what client you're using, I am assuming the web client.

https://github.com/jellyfin/jellyfin-web
