### ISSUE TITLE
Is there a reason to not look for folder(s) inside CBR archive?

### ISSUE THREAD

**Issue by AndyADD** [jellyfin/jellyfin-plugin-bookshelf#63]
Hello, I normally don't make issues on GitHub, pardon my ignorance. When I was trying to load a CBR comic through Jellyfin, I never got past the loading animation. 

When I dug around I discovered that when I unrar CBR file there was a folder with the images of the comic inside, so I rared the images, no folder, with CBR extension and Jellyfin was able to instantly load the comic, which is odd since it loads comics with .cbz extension that has a folder.

I never did a pull request, and figured maybe adding code to search for folder/files inside CBR archive would be simple enough for my first pull request.

But I wanted to ask if there a reason this hasn't been done already for CBR? Is it an underlying issue with RAR type archives?

Again, sorry for my ignorance.

**Comment by leaderdog** [comment]
I've run into this issue as well.  Folders inside a rar file are not able to be opened, where cbz files have no problem reading images inside a folder.

Is this something that will be fixed?  For reasons I choose not to convert the cbr files to cbz, which is a simple enough solution, but will cause other issues that I don't want to deal with.

If this is something that the author can't or refuses to fix I can respect that and I'll just continue to use Komga.

I'm pretty impressed with Bookshelf overall except this is rather a game breaker.

Thanks

**Comment by crobibero** [comment]
rar is a proprietary archive format so there arent any libraries to extract from it. Support will not be added.
