### ISSUE TITLE
M4b audiobooks not playable via safari or IOS app

### ISSUE THREAD

**Issue by CunningSquirrel** [jellyfin/jellyfin-plugin-bookshelf#69]
Bookshelf plug-in has been installed on Jellyfin Server running on Raspberry pi 4. Version 10.8.7

attempting to play audiobooks from IOS or web browser results in following error:

Playback Error
This client isn't compatible with the media and the server isn't sending a compatible media format.

**Comment by crobibero** [comment]
This plugin only provides metadata.
