### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by FelixSchwarz** [jellyfin/jellyfin-plugin-bookshelf#91]
How about creating a new release with the changes since v9? #67 lists already a few nice changes which I would like to enjoy.
I tried compiling the plugin myself but it did not work inside jellyfin for some reason (probably a different .NET SDK or incompatible build settings).

**Comment by crobibero** [comment]
Thanks for the reminder, v10 is now available.

**Comment by FelixSchwarz** [comment]
Thanks!
